dist: xenial
language: python
python:
- '2.7'
- '3.6'
- '3.7'
install:
- pip install -r requirements.txt
script:
- pylint --rcfile=.pylintrc graphdiff/graphdiff.py
deploy:
  provider: pypi
  user: yeger00@gmail.com
  password:
    secure: B9TXEl+jBxXZ4pt3OdWcUo3OwSLOG+UlC5VRjtul4Z92IYppIvc38AAjG79faSRPX5weXNEkteZirwlIZHlmGLzZsxAlWHvmtct8Zwh7NqtWXILkhuhmLNY6NdsxwNdvDX25kO14P+G/zcx9floWXetmIRAcbHUuO0cCtoFl+HGOLtZ+klSBknUmOM7bSlDPNgJ0dAK/ArVAEOlN/sZ7zoIJFd+BLmt6HhBnG+hLplIJNpDfN57jbgPbUF3m0XppJIL8os/akAganwuVUgVO3tE4BDn7CgmfPh4AjPCScse9KUmblBp2ZvzEDwLuNHzgXT0+Mmil4boq6H4Ns/yMH7aiIHHKhwpgzHCgnaFmXwAzhAcwsv9qO7+xCCWmfETglN3APHjG73Cf7/LKp33ckKNt46dX2JRZXd6o2zB0l065YLCtAWkor0TtMj3QYttiwL+Odur+tAk3/ME1k9PHmZFWTQQ/GyCl+nAZ7uhmtpCVleJbxSluMjq1Y4cPBIar17oVhUfGcWVZB5HPXk0PJ49e0f7xrI3yw93JknTsbDSpdF3MHekeH0Qe596D1vEaPPjBoE0QLlyYW9yziPeFC1uAA2Pk5mfPwXci3BsY798L0ZxyCIf6XSuHChEffCKDmt9vYy6GNNsFXYNirjMhuTkYipQdUC6j/6ydocdb18o=
  on:
    tags: true
